import React from "react";

//Searchable but need Styling

export default function BandaraTujuan() {
  return (
    <form>
      <input list="kota" name="kot" id="kot" />
      <datalist id="kota">
        <option value="BTJ">(BTJ) Banda Aceh, Sultan Iskandar Muda</option>
        <option value="MES">(MES) Medan, Polonia</option>
        <option value="BTH">(BTH) Batam, Hang Nadim</option>
        <option value="TNJ">(TNJ) Tanjung Pinang, Raja Haji Fisabilillah</option>
        <option value="PKU">(PKU) Pekanbaru, Sultan Syarif Kasim II</option>
        <option value="PDG">(PDG) Padang, Minangkabau</option>
        <option value="PLM">(PLM) Palembang, Sultan Mahmud Badaruddin II</option>
        <option value="BKS">(BKS) Bengkulu, Fatmawati Soekarno</option>
        <option value="TKG">(TKG) Bandar Lampung, Radin Inten II</option>
        <option value="CGK">(CGK) Jakarta, Soekarno-Hatta</option>
        <option value="HLP">(HLP) Jakarta, Halim Perdanakusuma</option>
        <option value="SUB">(SUB) Surabaya, Juanda</option>
        <option value="SOC">(SOC) Solo, Adisumarmo</option>
        <option value="JOG">(JOG) Yogyakarta, Adi Sucipto</option>
        <option value="SRG">(SRG) Semarang, Achmad Yani</option>
        <option value="BDO">(BDO) Bandung, Husein Sastranegara</option>
        <option value="DPS" selected>
          (DPS) Denpasar, Ngurah Rai
        </option>
        <option value="AMI">(AMI) Mataram, Selaparang</option>
        <option value="KOE">(KOE) Kupang , El Tari</option>
        <option value="BPN">(BPN) Balikpapan, Sepinggan</option>
        <option value="PNK">(PNK) Pontianak, Supadio</option>
        <option value="TRK">(TRK) Tarakan, Juwata</option>
        <option value="UPG">(UPG) Makassar, Sultan Hasanuddin</option>
        <option value="MDC">(MDC) Manado, Sam Ratulangi</option>
        <option value="AMQ">(AMQ) Ambon, Pattimura</option>
        <option value="DJJ">(DJJ) Jayapura, Sentani</option>
        <option value="BIK">(BIK) Biak, Frans Kaisiepo</option>
        <option value="TIM">(TIM) Tembagapura, Mozes Kilangin</option>
        <option value="MKQ">(MKQ) Merauke, Mopah</option>
        <option value="SBG">(SBG) Sabang, Maimun Saleh</option>
        <option value="LSX">(LSX) Aceh Utara, Lhok Sukon</option>
        <option value="LSW">(LSW) Lhokseumawe, Malikus Saleh</option>
        <option value="MEQ">(MEQ) Nagan Raya, Cut Nyak Dhien</option>
        <option value="TPK">(TPK) Tapaktuan, Teuku Cut Ali</option>
        <option value="SKL">(SKL) Singkil, Syekh Hamzah Fansyuri</option>
        <option value="SNB">(SNB) Sinabang, Lasikin</option>
        <option value="SIW">(SIW) Toba Samosir, Sibisa</option>
        <option value="SQT">(SQT) Siborong-borong, Silangit</option>
        <option value="SIX">(SIX) Sibolga, Dr. Ferdinand Lumban Tobing</option>
        <option value="AEG">(AEG) Padang Sidempuan, Aek Godang</option>
        <option value="GNS">(GNS) Gunung Sitoli, Binaka</option>
        <option value="LSE">(LSE) Pulau-pulau Batu, Lasondre</option>
        <option value="DUM">(DUM) Dumai, Pinang Kampai</option>
        <option value="SEQ">(SEQ) Bengkalis, Sungai Pakning</option>
        <option value="PPR">(PPR) Pasir Pengaraian, Pasir Pengaraian</option>
        <option value="SIQ">(SIQ) Singkep, Dabo</option>
        <option value="RGT">(RGT) Rengat, Japura</option>
        <option value="TJB">(TJB) Karimun, Sei Bati</option>
        <option value="NTX">(NTX) Natuna, Ranai</option>
        <option value="MWK">(MWK) Pal Matak, Matak</option>
        <option value="RKO">(RKO) Sipura, Rokot</option>
        <option value="DJB">(DJB) Jambi, Sultan Thaha Syarifuddin</option>
        <option value="KRC">(KRC) Kerinci, Depati Parbo</option>
        <option value="BKS">(BKS) Bengkulu, Fatmawati Soekarno</option>
        <option value="MPC">(MPC) Mukomuko, Mukomuko</option>
        <option value="PGK">(PGK) Pangkalpinang, Depati Amir</option>
        <option value="TJQ">(TJQ) Tanjung Pandan, H. A. S. Hanandjoeddin </option>
        <option value="LLG">(LLG) Lubuklinggau, Silampari</option>
        <option value="PDO">(PDO) Empat Lawang, Pendopo</option>
        <option value="PCB">(PCB) Pamulang, Pondok Cabe</option>
        <option value="PPJ">(PPJ) Kepulauan Seribu, Pulau Panjang</option>
        <option value="TSY">(TSY) Tasikmalaya, Cibeureum</option>
        <option value="CBN">(CBN) Cirebon, Cakrabhuwana</option>
        <option value="CXP">(CXP) Cilacap, Tunggul Wulung</option>
        <option value="PWL">(PWL) Purbalingga, Wirasaba</option>
        <option value="KWB">(KWB) Karimunjawa, Dewa Daru</option>
        <option value="CPF">(CPF) Cepu, Ngloram</option>
        <option value="MLG">(MLG) Malang, Abdul Rachman Saleh</option>
        <option value="SUP">(SUP) Sumenep, Trunojoyo</option>
        <option value="MSI">(MSI) Masalembo, Masalembo</option>
        <option value="SWQ">(SWQ) Sumbawa Besar, Brangbiji</option>
        <option value="LYK">(LYK) Sumbawa, Lunyuk</option>
        <option value="BMU">(BMU) Bima, Muhammad Salahuddin</option>
        <option value="KOE">(KOE) Kupang, El Tari</option>
        <option value="LBJ">(LBJ) Manggarai Barat, Komodo</option>
        <option value="RTG">(RTG) Ruteng, Frans Sales Lega</option>
        <option value="TMC">(TMC) Waikabubak, Tambolaka</option>
        <option value="WGP">(WGP) Waingapu, Mau Hau</option>
        <option value="BJW">(BJW) Bajawa, Soa</option>
        <option value="ENE">(ENE) Ende, H Hasan Aroeboesman</option>
        <option value="MOF">(MOF) Maumere, Wai Oti</option>
        <option value="LKA">(LKA) Larantuka, Gewayantana</option>
        <option value="LWE">(LWE) Lewoleba, Wonopito</option>
        <option value="ARD">(ARD) Alor, Mali</option>
        <option value="RTI">(RTI) Rote, Lekunik</option>
        <option value="SAU">(SAU) Pulau Sawu, Tardamu</option>
        <option value="ABU">(ABU) Atambua, Haliwen</option>
        <option value="KTG">(KTG) Ketapang, Rahadi Oesman</option>
        <option value="SQG">(SQG) Sintang, Susilo</option>
        <option value="NPO">(NPO) Nanga Pinoh, Nanga Pinoh</option>
        <option value="PSU">(PSU) Putussibau, Pangsuma</option>
        <option value="PKY">(PKY) Palangka Raya, Tjilik Riwut</option>
        <option value="PKN">(PKN) Pangkalan Bun, Iskandar</option>
        <option value="TBM">(TBM) Katingan, Tumbang Samba</option>
        <option value="SMQ">(SMQ) Sampit, H. Asan</option>
        <option value="MTW">(MTW) Muara Teweh, Beringin</option>
        <option value="BDJ">(BDJ) Banjarmasin, Syamsuddin Noor</option>
        <option value="TJG">(TJG) Tanjung, Warukin</option>
        <option value="BTW">(BTW) Batulicin, Bersujud</option>
        <option value="KBU">(KBU) Kotabaru, Stagen</option>
        <option value="SRI">(SRI) Samarinda, Temindung</option>
        <option value="NNX">(NNX) Nunukan, Nunukan</option>
        <option value="LBW">(LBW) Krayan, Yuvai Semaring</option>
        <option value="BYQ">(BYQ) Pulau Bunyu, Bunyu</option>
        <option value="MLN">(MLN) Malinau, R.A. Bessing</option>
        <option value="LPU">(LPU) Kayan Selatan, Long Ampung</option>
        <option value="TJS">(TJS) Tanjung Selor, Tanjung Harapan</option>
        <option value="NAF">(NAF) Bulungan, Banaina</option>
        <option value="BEJ">(BEJ) Tanjung Redeb, Kalimarau</option>
        <option value="SGQ">(SGQ) Sangatta, Sangkimah</option>
        <option value="BXT">(BXT) Bontang, Bontang</option>
        <option value="TSX">(TSX) Marang Kayu, Tanjung Santan</option>
        <option value="KOD">(KOD) Kutai Kartanegara, Kotabangun</option>
        <option value="SZH">(SZH) Kutai Kartanegara, Senipah</option>
        <option value="MLK">(MLK) Melak, Melalan</option>
        <option value="DTD">(DTD) Kutai Barat, Datah Dawai</option>
        <option value="TNB">(TNB) Tanah Grogot, Tanah Grogot</option>
        <option value="SGQ">(SGQ) Tanjung Sangatta, Bara</option>
        <option value="MXB">(MXB) Masamba, Andi Djemma</option>
        <option value="BUW">(BUW) Bau-bau, Betoambari</option>
        <option value="GTO">(GTO) Gorontalo, Jalaluddin</option>
        <option value="SQR">(SQR) Sorowako, Inco Soroako Waws</option>
        <option value="PSJ">(PSJ) Poso, Kasiguncu</option>
        <option value="TLI">(TLI) Tolitoli, Lalos</option>
        <option value="MJU">(MJU) Mamuju, Tampa Padang</option>
        <option value="MNA">(MNA) Melonguane, Melonguane</option>
        <option value="BJG">(BJG) Bolaang Mongondow, Mopait</option>
        <option value="PLW">(PLW) Palu, Mutiara</option>
        <option value="NAH">(NAH) Tahuna, Naha</option>
        <option value="UOL">(UOL) Buol, Pogugol</option>
        <option value="PUM">(PUM) Pomalaa, Pomalaa</option>
        <option value="TTR">(TTR) Tana Toraja, Pongtiku</option>
        <option value="RAQ">(RAQ) Raha, Sugimanuru</option>
        <option value="LUW">(LUW) Luwuk, Syukuran Aminuddin Amir</option>
        <option value="KDI">(KDI) Kendari, Haluoleo</option>
        <option value="KSR">(KSR) H Selayar, Aroeppala </option>
        <option value="WNI">(WNI) Matahora Wangi-wangi, Wakatobi</option>
        <option value="AHI">(AHI) Masohi, Amahai</option>
        <option value="NDA">(NDA) Banda, Bandaneira</option>
        <option value="DOB">(DOB) Kepulauan Aru, Dobo</option>
        <option value="LUV">(LUV) Langgur, Dumatubun</option>
        <option value="SQN">(SQN) Sanana, Emalamo</option>
        <option value="GLX">(GLX) Galela, Gamarmalamo</option>
        <option value="GEB">(GEB) Gebe, Gebe</option>
        <option value="KAZ">(KAZ) Tobelo, Kuabang</option>
        <option value="MAL">(MAL) Mangole, Mangole</option>
        <option value="NAM">(NAM) Namlea, Namlea</option>
        <option value="NRE">(NRE) Namrole, Namrole</option>
        <option value="BJK">(BJK) Benjina, Nangasuri</option>
        <option value="LAH">(LAH) Labuha, Oesman Sadik</option>
        <option value="SXK">(SXK) Saumlaki, Olilit</option>
        <option value="OTI">(OTI) Morotai, Pitu</option>
        <option value="TTE">(TTE) Ternate, Sultan Babullah</option>
        <option value="TAX">(TAX) Taliabu, Taliabu</option>
        <option value="WHI">(WHI) Pulau Seram, Wahai</option>
        <option value="PCG">(PCG) Buli, Maba</option>
        <option value="RSK">(RSK) Manokwari, Abresso</option>
        <option value="AGD">(AGD) Anggi, Anggi</option>
        <option value="AAS">(AAS) Jayawijaya, Apalapsili</option>
        <option value="ARJ">(ARJ) Arso, Arso</option>
        <option value="AYW">(AYW) Sorong, Ayawasi</option>
        <option value="BXB">(BXB) Babo, Babo</option>
        <option value="BXD">(BXD) Merauke, Bade</option>
        <option value="BXM">(BXM) Pegunungan Bintang, Batom</option>
        <option value="NTI">(NTI) Bintuni, Bintuni</option>
        <option value="BUI">(BUI) Jayawijaya, Bokondini</option>
        <option value="DRH">(DRH) Puncak Jaya, Dabra</option>
        <option value="ELR">(ELR) Jayawijaya, Elilim</option>
        <option value="EWI">(EWI) Enarotali, Enarotali</option>
        <option value="EWE">(EWE) Merauke, Ewer</option>
        <option value="ILA">(ILA) Paniai, Illaga</option>
        <option value="IUL">(IUL) Puncak Jaya, Ilu</option>
        <option value="INX">(INX) Inanwatan, Inanwatan</option>
        <option value="SOQ">(SOQ) Sorong, Jeffman</option>
        <option value="FOO">(FOO) Numfor Timur, Yemburwo.</option>
        <option value="KBX">(KBX) Sorong Selatan, Kambuaya</option>
        <option value="KCD">(KCD) Asmat, Kamur</option>
        <option value="KBF">(KBF) Jayawijaya, Karubaga</option>
        <option value="KEQ">(KEQ) Manokwari, Kebar</option>
        <option value="LLN">(LLN) Jayawijaya, Kelila</option>
        <option value="KEI">(KEI) Merauke, Kepi</option>
        <option value="KMM">(KMM) Merauke, Kimaan</option>
        <option value="KOX">(KOX) Mimika, Kokonao</option>
        <option value="LHI">(LHI) Jayapura, Lereh</option>
        <option value="ZRM">(ZRM) Sarmi, Mararena</option>
        <option value="RDE">(RDE) Manokwari, Merdey</option>
        <option value="MDP">(MDP) Boven Digoel, Mindiptana</option>
        <option value="ONI">(ONI) Dogiyai, Moanamani</option>
        <option value="LII">(LII) Puncak Jaya, Mulia</option>
        <option value="MUF">(MUF) Merauke, Muting</option>
        <option value="NBX">(NBX) Nabire, Nabire</option>
        <option value="OBD">(OBD) Nabire, Obano</option>
        <option value="OKQ">(OKQ) Puncak Jaya, Okaba</option>
        <option value="OKL">(OKL) Pegunungan Bintang, Oksibil</option>
        <option value="GAV">(GAV) Raja Ampat, Pulau Gag</option>
        <option value="MKW">(MKW) Manokwari, Rendani</option>
        <option value="SEH">(SEH) Keerom, Senggeh</option>
        <option value="ZEG">(ZEG) Mappi, Senggo</option>
        <option value="NKD">(NKD) Puncak Jaya, Sinak</option>
        <option value="ZRI">(ZRI) Serui, Sudjarwo Tjondronegoro</option>
        <option value="TMH">(TMH) Tanah Merah, Tanah Merah</option>
        <option value="TXM">(TXM) Teminabuan, Teminabuan</option>
        <option value="TMY">(TMY) Jayawijaya, Tiom</option>
        <option value="FKQ">(FKQ) Fakfak, Torea</option>
        <option value="UBR">(UBR) Keerom, Ubrub</option>
        <option value="KNG">(KNG) Kaimana, Utarom</option>
        <option value="WET">(WET) Deiyai, Waghete</option>
        <option value="WMX">(WMX) Wamena, Wamena</option>
        <option value="WAR">(WAR) Keerom, Waris</option>
        <option value="WSR">(WSR) Wasior, Wasior</option>
        <option value="RUF">(RUF) Jayawijaya, Yuruf</option>
        <option value="UGU">(UGU) Paniai, Zugapa</option>
        <option value="SOQ">(SOQ) Sorong, Domine Eduard Osok </option>
      </datalist>
    </form>
  );
}
